server: server.go database.go querytypes.go
	go build server.go database.go querytypes.go mimetypes.go
all:
	go build main.go database.go
other:
	#go build reflect.go
	#go build server.go database.go
